name: RJ_project_pipeline
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML container
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      # may need to setup Node.js & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: Train model
        run: |
          # Your ML workflow goes here
<<<<<<< HEAD
          pip install numpy
=======
          pip install --upgrade pip
          pip install numpy
>>>>>>> cd4a3e1a213c6d124f11c56e6d031cdf421dece2
          pip install -r requirements.txt
          python ./LicensePlateRecognition/main_2_indian_num_plate.py  # generate plot.png
